# Generated by Django 4.1.2 on 2022-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Gaming', 'Gaming'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Unassigned', 'Unassigned')], default='Unassigned', max_length=25),
        ),
        migrations.AddField(
            model_name='article',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('Drafts', 'Drafts'), ('Submitted', 'Submitted'), ('Published', 'Published'), ('Rejected', 'Rejected'), ('Archived', 'Archived'), ('Unassigned', 'Unassigned')], default='Drafts', max_length=25),
        ),
    ]
